name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup .net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      - name: Restore
        run: dotnet restore ./WebAppDeploy.sln

      - name: Build
        run: dotnet build ./WebAppDeploy.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./WebAppDeploy.sln --configuration Release --no-build
