name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: deploy-teste-ci-cd
  AZURE_WEBAPP_PACKAGE_PATCH: "./publish"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Lint
        run: echo "Lint project"
  
  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup .net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      - name: Run Integration Tests
        run: dotnet test --filter Category=Integration --no-restore --verbosity normal     

  build:
    needs: [lint,test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup .net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      - name: Test
        run: echo "Test project"      

      - name: Restore
        run: dotnet restore ./WebAppDeploy.sln

      - name: Build
        run: dotnet build ./WebAppDeploy.sln --configuration Release --no-restore

  publish:
    needs: [build, lint, test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup .net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      - name: Restore
        run: dotnet restore ./WebAppDeploy.sln

      - name: Build
        run: dotnet build ./WebAppDeploy.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./WebAppDeploy.sln --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATCH }}'

      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATCH }}
